version: "3"
services:
  # Scraping database
  database:
    container_name: scraping_database
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./src/db_scripts/queries:/home

  # Twitter streaming
  twitter_streaming:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: [ "python", "src/twitter_streaming/twitter_tracker.py" ]
    restart: on-failure
    volumes:
      - ./data/raw:/home/fullstack_ml/data/raw

volumes:
  db_volume:
