version: "3"

services:
  ### PYTHON POETRY ###
  python_poetry:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command:
      [
        "jupyter",
        "lab",
        "--no-browser",
        "--ip",
        "0.0.0.0",
        "--port",
        "8787",
        "--allow-root"
      ]
    restart: on-failure
    ports:
      - "8787:8787"
    volumes:
      - ./notebooks:/home/src/notebooks
