version: "3"

services:
  ### POSTGRE DATABASE ###
  database:
    container_name: postgres
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  ### PYTHON POETRY ###
  python_poetry:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command:
      [
        "jupyter",
        "lab",
        "--no-browser",
        "--ip",
        "0.0.0.0",
        "--port",
        "8787",
        "--allow-root"
      ]
    restart: on-failure
    ports:
      - "8787:8787"
    volumes:
      - ./notebooks:/home/src/notebooks
    depends_on:
      - database

volumes:
  db_volume:
