apiVersion: batch/v1
kind: CronJob
metadata:
  name: bitcoin-crawler-cronjob
spec:
  schedule: "0 23 * * *" # Run at 23:00 UTC every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bitcoin-crawler
              image: gcr.io/full-stack-ml-challenge/python-poetry:latest
              command: ["/bin/sh", "-c"]
              args:
                - src/bash/bitcoin-cronjob.sh "$(date -d 'today' +%F)"
          imagePullSecrets:
            - name: gcr-json-key
          restartPolicy: OnFailure
