apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting-api
spec:
  selector:
    matchLabels:
      app: forecasting-api
  replicas: 1
  template:
    metadata:
      labels:
        app: forecasting-api
    spec:
      containers:
        - name: python
          image: gcr.io/full-stack-ml-challenge/python-poetry:v1.1
          command: ["python", "src/api/forecasting_api.py"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: models-volume
              mountPath: /home/fullstack_ml/models/forecasting
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: forecasting-api
spec:
  selector:
    app: forecasting-api
  type: NodePort
  ports:
    - nodePort: 30002
      port: 8000
      targetPort: 8000
